### ISSUE TITLE
How to run It

### ISSUE THREAD

**Issue by deepkshikha** [ghostbbbmt/NVIDIA-DeepStreamSDK#2]
What are the steps or any hint how to run it. Can I use Volta 100 for it

**Comment by hoanglehaithanh** [comment]
You can read the user guide to run this project at https://github.com/ghostbbbmt/NVIDIA-DeepStreamSDK/blob/master/doc/DeepStream_User_Guide.pdf

You can use Volta or even GTX GPU to run DeepStream. Please make sure you satisfied all requirements.

Please notice that the version of this repo's SDK is 1.5, which is an old version but very easy to use for simple projects or newbies. You might try the latest 2.0 version on NVIDIA website

Sorry for this late reply. I am currently busy with new tasks, so this repo will be updated in the far future
